/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create session (login)
         * @description Authenticate user and receive an API token
         */
        post: operations["login"];
        /**
         * Destroy session (logout)
         * @description Revoke the current API token
         */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recipes
         * @description Get all recipes for the authenticated user
         */
        get: operations["getRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recipe details
         * @description Get full details for a specific recipe
         */
        get: operations["getRecipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add recipe to favorites
         * @description Mark a recipe as favorite (idempotent)
         */
        put: operations["addFavorite"];
        post?: never;
        /**
         * Remove recipe from favorites
         * @description Unmark a recipe as favorite (idempotent)
         */
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @description User ID */
            id: number;
            /**
             * Format: email
             * @description User email address
             */
            email: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User email address
             */
            email: string;
            /** @description User password */
            password: string;
            /** @description Optional device name for token identification */
            device_name?: string;
        };
        LoginResponse: {
            /** @description Bearer token for API authentication */
            token: string;
            /**
             * Format: date-time
             * @description Token expiration timestamp
             */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        LogoutResponse: {
            /** @example Logged out successfully */
            message: string;
        };
        Tag: {
            /** @description Tag ID */
            id: number;
            /** @description Tag name */
            name: string;
        };
        RecipeListItem: {
            /** @description Recipe ID */
            id: number;
            /** @description Recipe name */
            name: string;
            /** @description Preparation time in minutes */
            prep_time?: number | null;
            /** @description Cooking time in minutes */
            cook_time?: number | null;
            /** @description Whether recipe is marked as favorite */
            favorite: boolean;
            /**
             * Format: uri
             * @description URL to recipe thumbnail image
             */
            cover_image_url?: string | null;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        RecipeDetail: {
            /** @description Recipe ID */
            id: number;
            /** @description Recipe name */
            name: string;
            /** @description Preparation time in minutes */
            prep_time?: number | null;
            /** @description Cooking time in minutes */
            cook_time?: number | null;
            /** @description Number of servings */
            servings?: number | null;
            /** @description Whether recipe is marked as favorite */
            favorite: boolean;
            /** @description List of ingredients */
            ingredients: string[];
            /** @description Cooking instructions (may contain markdown) */
            instructions: string | null;
            /** @description Additional notes */
            notes?: string | null;
            /**
             * Format: uri
             * @description Original recipe source URL
             */
            source_url?: string | null;
            /** @description Recipe tags/categories */
            tags: components["schemas"]["Tag"][];
            /**
             * Format: uri
             * @description URL to recipe display image
             */
            cover_image_url?: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        FavoriteResponse: {
            /** @description Recipe ID */
            id: number;
            /** @description Current favorite status */
            favorite: boolean;
        };
        Error: {
            /** @description Error message */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successfully authenticated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Invalid email or password"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many login attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Too many login attempts. Try again later."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRecipes: {
        parameters: {
            query?: {
                /** @description Filter to only show favorites */
                favorites?: "true";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListItem"][];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Recipe not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe ID */
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe favorited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "favorite": true
                     *     }
                     */
                    "application/json": components["schemas"]["FavoriteResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Recipe not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe ID */
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe unfavorited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 1,
                     *       "favorite": false
                     *     }
                     */
                    "application/json": components["schemas"]["FavoriteResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Recipe not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
