# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Exclude mobile app directory (has its own tooling)
AllCops:
  Exclude:
    - "hauptgang-mobile/**/*"

# Load custom cops from lib/rubocop/cop
require:
  - ./lib/rubocop/cop/hauptgang/scoped_recipe_query

# Enable custom cops
Hauptgang/ScopedRecipeQuery:
  Enabled: true
  Description: "Detects unscoped Recipe queries that leak data across users"

# Complexity Metrics
Metrics/CyclomaticComplexity:
  Max: 10  # Default is 7, adjust based on your needs

Metrics/PerceivedComplexity:
  Max: 10  # Accounts for human perception of complexity

Metrics/AbcSize:
  Max: 20  # Assignment, Branch, Condition size

Metrics/MethodLength:
  Max: 15
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 25
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
