dbs:
  - path: /rails/storage/production.sqlite3
    replicas:
      - type: s3
        bucket: ${LITESTREAM_REPLICA_BUCKET}
        path: production.sqlite3
        endpoint: ${LITESTREAM_REPLICA_ENDPOINT}
        access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
        retention: 72h
        snapshot-interval: 24h
