# SwiftLint Configuration for Hauptgang iOS

# Paths to exclude from linting
excluded:
  - Pods
  - build
  - DerivedData
  - .build

# Paths to include
included:
  - Hauptgang
  - ImportRecipeExtension

# Rules to enable
opt_in_rules:
  # Existing complexity rules
  - closure_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - file_length
  - type_body_length
  - function_body_length
  - large_tuple
  - nesting

  # Code quality
  - empty_count                              # Use .isEmpty instead of count == 0
  - empty_string                             # Use .isEmpty instead of == ""
  - contains_over_first_not_nil             # Use contains instead of first(where:) != nil
  - first_where                              # Use first(where:) instead of filter + first
  - last_where                               # Use last(where:) instead of filter + last
  - contains_over_filter_count              # Use contains instead of filter + count
  - contains_over_filter_is_empty           # Use contains instead of filter + isEmpty
  - empty_collection_literal                # Use isEmpty to check for empty collection

  # Style & formatting
  - closure_spacing                          # Closure should have a single space inside each brace
  - multiline_parameters                    # Functions should have arguments on same line or one per line
  - sorted_imports                           # Imports should be sorted alphabetically
  - vertical_whitespace_closing_braces      # Don't include vertical whitespace before closing braces
  - vertical_whitespace_opening_braces      # Don't include vertical whitespace after opening braces
  - operator_usage_whitespace               # Operators should be surrounded by whitespace
  - redundant_type_annotation               # Variables should not have redundant type annotation

  # Best practices
  - discouraged_optional_collection         # Prefer non-optional collections
  - explicit_init                            # Use .init() instead of Type()
  - fallthrough                              # Fallthrough should be avoided
  - fatal_error_message                      # fatalError should have a message
  - force_unwrapping                         # Force unwrapping should be avoided
  - implicitly_unwrapped_optional           # Implicitly unwrapped optionals should be avoided
  - let_var_whitespace                       # Let and var should be separated by a blank line
  - multiline_function_chains               # Chained function calls should be on separate lines
  - overridden_super_call                    # Some methods should always call super
  - prohibited_super_call                    # Some methods should not call super
  - redundant_nil_coalescing                # nil coalescing operator is redundant
  - toggle_bool                              # Prefer someBool.toggle() over someBool = !someBool
  - unavailable_function                     # Unimplemented functions should be marked as unavailable
  - unneeded_parentheses_in_closure_argument # Parentheses are not needed in closure
  - yoda_condition                           # Variables should be on left side of comparisons

  # Swift Concurrency
  - async_without_await                      # async functions should contain await
  - actor_mark                               # Actor properties should be marked with @MainActor when needed

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: false

# Function Body Length
function_body_length:
  warning: 40
  error: 60

# Type Body Length (class/struct/enum)
type_body_length:
  warning: 300
  error: 400

# File Length
file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

# Function Parameter Count
function_parameter_count:
  warning: 6
  error: 8

# Nesting (nested types/functions)
nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

# Large Tuple (complexity indicator)
large_tuple:
  warning: 3
  error: 4

# Line Length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Identifier Name
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - to
    - in
    - db

# Reporter
reporter: "xcode"
