name: Hauptgang
options:
  bundleIdPrefix: app.hauptgang
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  Hauptgang:
    type: application
    platform: iOS
    sources:
      - path: Hauptgang
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.hauptgang.ios
      INFOPLIST_FILE: Hauptgang/Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: NO
      SWIFT_EMIT_LOC_STRINGS: YES
    dependencies: []

  HauptgangTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HauptgangTests
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.hauptgang.ios.tests
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Hauptgang.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Hauptgang"
      BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Hauptgang

schemes:
  Hauptgang:
    build:
      targets:
        Hauptgang: all
        HauptgangTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HauptgangTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
