name: Hauptgang
options:
  bundleIdPrefix: app.hauptgang
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    from: 5.0.0

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "6"
  # Enable Swift 6 strict concurrency checking for data race safety
  SWIFT_STRICT_CONCURRENCY: complete

targets:
  Hauptgang:
    type: application
    platform: iOS
    sources:
      - path: Hauptgang
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.hauptgang.ios
      INFOPLIST_FILE: Hauptgang/Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_ENTITLEMENTS: Hauptgang/Hauptgang.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: NO
      SWIFT_EMIT_LOC_STRINGS: YES
    dependencies:
      - target: ImportRecipeExtension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins
          subpath: ""
      - package: RevenueCat
        product: RevenueCat
      - package: RevenueCat
        product: RevenueCatUI

  ImportRecipeExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ImportRecipeExtension
        excludes:
          - "**/.DS_Store"
      # Shared code from main app
      - path: Hauptgang/Services/APIClient.swift
      - path: Hauptgang/Services/APIClientProtocol.swift
      - path: Hauptgang/Services/KeychainService.swift
      - path: Hauptgang/Models/APIError.swift
      - path: Hauptgang/Models/User.swift
      - path: Hauptgang/Utilities/Constants.swift
      - path: Hauptgang/Models/ImportRecipeResponse.swift
      - path: Hauptgang/Services/RecipeImportService.swift
      - path: Hauptgang/Services/ImageCompressor.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.hauptgang.ios.share-extension
      INFOPLIST_FILE: ImportRecipeExtension/Info.plist
      CODE_SIGN_ENTITLEMENTS: ImportRecipeExtension/ImportRecipeExtension.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      SKIP_INSTALL: YES
      GENERATE_INFOPLIST_FILE: NO
    dependencies: []

  HauptgangTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HauptgangTests
        excludes:
          - "**/.DS_Store"
      # Include ShareImportExtractor for testing
      - path: ImportRecipeExtension/ShareImportExtractor.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.hauptgang.ios.tests
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Hauptgang.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Hauptgang"
      BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Hauptgang

schemes:
  Hauptgang:
    build:
      targets:
        Hauptgang: all
        HauptgangTests: [test]
    run:
      config: Debug
      storeKitConfiguration: Hauptgang-StoreKit.storekit
    test:
      config: Debug
      targets:
        - HauptgangTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
